{{- range $component, $config := .Values.components }}
{{- if and $config.enabled $config.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $component }}
  labels:
    {{- include "voting-app.labels" $ | nindent 4 }}
  {{- with $config.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
