apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30001
      name: "vote-service"
  selector:
    app: vote