apiVersion: v1
kind: Pod
metadata: 
  name: worker
  labels:
    app: worker
spec:
  containers:
    - name: worker 
      image: dockersamples/examplevotingapp_worker:latest
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
        